<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.encoder_factory.generic' shared service.

return $this->privates['security.encoder_factory.generic'] = new \Symfony\Component\Security\Core\Encoder\EncoderFactory(array('App\\Entity\\User' => array('class' => 'Symfony\\Component\\Security\\Core\\Encoder\\Argon2iPasswordEncoder', 'arguments' => array(0 => NULL, 1 => NULL, 2 => NULL))));
