version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: docker-symfony4-mysql
      working_dir: /backend
      volumes:
        - ./backend:/backend
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=rest-backend
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
      ports:
        - "127.0.3.3:8002:3306"

    backend-server:
      image: nginx:alpine
      container_name: docker-rest-backend-server
      working_dir: /backend
      volumes:
          - ./backend:/backend
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "127.0.3.2:80:80"
      depends_on:
       - mysql

    php-fpm:
      build: phpdocker/php-fpm
      container_name: docker-rest-php-fpm
      working_dir: /backend
      volumes:
        - ./backend:/backend
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      depends_on:
       - mysql
