# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html

### TUTORIAL:
###  We want to separate the Rest controllers from our Web controllers
###  All our Rest calls should be prefixed by /api

fos_rest:
    body_converter:
        enabled: true
    view:
        view_response_listener: true
### use the fos_rest exception controller
### If we now send a  request to GET /api/articles/<wrong id>. We will get 404 Not Found response
    exception:
        exception_controller: 'fos_rest.exception.controller:showAction'
        codes:
            Doctrine\ORM\EntityNotFoundException: 404
    format_listener:
        rules:
        - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
### enable the converter to convert the Request object to our Data Transfer Object
