<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8MNeaNc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8MNeaNc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8MNeaNc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8MNeaNc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8MNeaNc\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => '8MNeaNc',
    'container.build_id' => '67751603',
    'container.build_time' => 1557059441,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8MNeaNc');
